---

steps:

  - name: ubuntu
    id: Build information
    entrypoint: bash
    args:
      - '-c'
      - |
        echo \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
        echo BUILD DETAILS:
        [ ! -z "${PROJECT_ID}" ]     && echo "Project ID:    ${PROJECT_ID}"
        [ ! -z "${BUILD_ID}" ]       && echo "Build ID:      ${BUILD_ID}"
        [ ! -z "${COMMIT_SHA}" ]     && echo "Commit SHA:    ${COMMIT_SHA}"
        [ ! -z "${SHORT_SHA}" ]      && echo "Short SHA:     ${SHORT_SHA}"
        [ ! -z "${REPO_NAME}" ]      && echo "Repo name:     ${REPO_NAME}"
        [ ! -z "${BRANCH_NAME}" ]    && echo "Branch name:   ${BRANCH_NAME}"
        [ ! -z "${TAG_NAME}" ]       && echo "Tag name:      ${TAG_NAME}"
        [ ! -z "${REVISION_ID}" ]    && echo "Revision ID:   ${REVISION_ID}"
        [ ! -z "${_HEAD_BRANCH}" ]   && echo "Head branch:   ${_HEAD_BRANCH}"
        [ ! -z "${_BASE_BRANCH}" ]   && echo "Base branch:   ${_BASE_BRANCH}"
        [ ! -z "${_HEAD_REPO_URL}" ] && echo "Head repo URL: ${_HEAD_REPO_URL}"
        [ ! -z "${_PR_NUMBER}" ]     && echo "PR number:     ${_PR_NUMBER}"
        echo \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
#
# Deploy code
#

  - name: hashicorp/terraform
    id: Terraform version
    args:
      - '-v'
    dir: infra/terraform/

  - name: hashicorp/terraform
    id: Terraform init
    args:
      - 'init'
      - '-backend-config=bucket=${PROJECT_ID}-state'
    dir: infra/terraform/

  - name: hashicorp/terraform
    id: Terraform plan
    args:
      - 'plan'
      - '-out=/workspace/tfplan'
    dir: infra/terraform/
  
# Environment variables
options:
  env:
    - GOOGLE_PROJECT=${PROJECT_ID}
    - GOOGLE_REGION=${_REGION}

timeout: 1800s # 30min, overriding the default 10min build timeout